### ISSUE TITLE
TabPane breaks native image build

### ISSUE THREAD

**Issue by krazilek** [gluonhq/gluon-samples#116]
Greetings to Gluon team!

I can successfully build runnable file of sample project HelloFXML, but when AnchorPane is replaced with TabPane, generated native image file is not runnable - seems as if exe is terminated right after launching. 

Additional info:
1) mvn gluonfx:run works fine -  
![TabPane-internal_launch](https://user-images.githubusercontent.com/13416897/123625260-a42e8f80-d820-11eb-87ba-fe785caeed12.png)
2) if TabPane creation is altered to manual initialization instead of loading from fxml file - native image is correct

So my questions are:
1) What's the difference of TabPane from AnchorPane, so that it becomes non-initializable from fxml file? 
2) Am I correct and this is the root reason of 'broken' image or there is something else? 
3) Is it fixable? 
4) It is expected that components described in fxml file will initialize/render/behave normally in native builds and if there's some kind of limits/restrictions, could you provide documentation links? 

**Expected Behavior**
Slight modification of sample project should result in runnable native image file.

**Current Behavior**
Launching exe file results in nothing - seems that it terminates so quickly that even no new process is seen in Task manager.

**Steps to Reproduce**
1) Replace src/main/resources/hellofx/hello.fxml file of gluon-samples/HelloFXML project with one in archive.
Replace src/main/java/hellofx/HelloFXML.java file of gluon-samples/HelloFXML project with one in archive.
[helloFXML.zip](https://github.com/gluonhq/gluon-samples/files/6725830/helloFXML.zip)
2) Build native image - using "x64 Native Tools Command Prompt for VS 2019" utility, from project dir execute:
mvn gluonfx:build
3) Launch result exe file 

**Your Environment**
OS - Windows 7 x64 Ultimate with SP1
Apache Maven 3.5.2 
Java version: 11.0.11, vendor: GraalVM Community (from GraalVM CE Gluon 21.1.0-dev-20210415_0700 build)
Java home: E:\work\graalvm-svm-windows-gluon-21.1.0-dev

**Comment by jperedadnr** [comment]
Did you try `gluonfx:runagent` before starting the build?

**Comment by krazilek** [comment]
> 
> 
> Did you try `gluonfx:runagent` before starting the build?

Thanks José, running runagent before the build solved problem. 

But it seems a little bit strange to me - as documentation says: "If needed, this goal should be executed before the others, and requires the user intervention to discover all reachable classes, by going through all possible scenes, views, dialogs, menus…​" , so I can imagine that for 'distant'/hidden tabs, dialogs or elements **runagent** process can prepare more detailed config files, but in this scenario we have root element that is problematic - and yet **runagent + build** is more resultative than **run + build**...

**Comment by jperedadnr** [comment]
`gluonfx:run` goal is on JVM, nothing to do with native-image. It is only needed to test that your app works fine.

`gluonfx:runagent` is on JVM too, but using GraalVM's agent to find and discover all reflective use cases, and generate the json config files that are used by the native-image tool. This depends on running all possible scenarios for a better discovery, but that doesn't mean you need to go through everything, as some classes might be loaded even if you don't visit them.

`gluonfx:build` shouldn't require `runagent` in some usual cases, because the plugin already includes some common reflection cases, however not 100% of JavaFX classes/methods are included, and when this happens, either you add it manually (`reflectionList` or reflection json files under META-INF/Substrate) or you let `runagent` find it for you (under `META-INF/native-image`).
