### ISSUE TITLE
Is there an example how to use Gluon with Gradle?

### ISSUE THREAD

**Issue by tadas-subonis** [gluonhq/gluon-samples#97]
Is there an example how to use Gluon with Gradle?

**Comment by PradeepSimba** [comment]
For more information: https://docs.gluonhq.com/client/

**Comment by abhinayagarwal** [comment]
@PradeepSimba The code posted by you use the `jfxmobile` plugin instead of the Gluon client plugin. The new plugin uses `attachConfig` instead of `downConfig`.

A few samples can be found here: https://github.com/abhinayagarwal/gluon-samples-gradle. Check the "HelloGluon" sample for attach configuration.

**Comment by PradeepSimba** [comment]
@abhinayagarwal  Good job.
